export const CURRENCIES = [
  { code: 'KRW', symbol: '₩', flag: '🇰🇷', name: '원' },
  { code: 'USD', symbol: '$', flag: '🇺🇸', name: '달러' },
  { code: 'JPY', symbol: '¥', flag: '🇯🇵', name: '엔' },
  { code: 'CNY', symbol: '¥', flag: '🇨🇳', name: '위안' },
  { code: 'EUR', symbol: '€', flag: '🇪🇺', name: '유로' },
  { code: 'GBP', symbol: '£', flag: '🇬🇧', name: '파운드' },
  { code: 'VND', symbol: '₫', flag: '🇻🇳', name: '동' },
  { code: 'THB', symbol: '฿', flag: '🇹🇭', name: '바트' },
  { code: 'TWD', symbol: 'NT$', flag: '🇹🇼', name: '대만 달러' },
  { code: 'HKD', symbol: 'HK$', flag: '🇭🇰', name: '홍콩 달러' },
  { code: 'SGD', symbol: 'S$', flag: '🇸🇬', name: '싱가포르 달러' },
  { code: 'MYR', symbol: 'RM', flag: '🇲🇾', name: '링깃' },
  { code: 'PHP', symbol: '₱', flag: '🇵🇭', name: '페소' },
  { code: 'IDR', symbol: 'Rp', flag: '🇮🇩', name: '루피아' },
  { code: 'AED', symbol: 'د.إ', flag: '🇦🇪', name: '디르함' },
  { code: 'TRY', symbol: '₺', flag: '🇹🇷', name: '리라' },
  { code: 'INR', symbol: '₹', flag: '🇮🇳', name: '루피' },
  { code: 'BRL', symbol: 'R$', flag: '🇧🇷', name: '헤알' },
]